
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Database&#58; Transactions - Crystal - W3cubDocs</title>
  
  <meta name="description" content="When working with databases, it is common to need to group operations in such a way that if one fails, then we can go back to the latest safe state &hellip;">
  <meta name="keywords" content="transactions, database, crystal">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/crystal/docs/database/transactions.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e4ebd3a2a5652ff55173659804c4390a004917f3bdd17b5bb3ba78ea5c9c46fe181cadaac34517ccd815f5bdc982bbfe67179d6f4ac2f084ef2265e2a3dc8dc5.css" integrity="sha512-5OvToqVlL/VRc2WYBMQ5CgBJF/O90Xtbs7p46lycRv4YHK2qw0UXzNgV9b3Jgrv+Zxedb0rC8ITvImXio9yNxQ==" crossorigin="anonymous">
  <script type="text/javascript" integrity="sha512-EpkDeu98lN/jPKijllzVWdRg/dUSSMCaldYZNFz6bcNoBvpWRNz0HSTRQJ3ENmQc5Cuj1zDW1vHd7b0DzpOgyA==" crossorigin="anonymous" src="/assets/application-1299037aef7c94dfe33ca8a3965cd559d460fdd51248c09a95d619345cfa6dc36806fa5644dcf41d24d1409dc436641ce42ba3d730d6d6f1ddedbd03ce93a0c8.js"></script>
  <script src="/json/crystal.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script data-ad-client="ca-pub-2572770204602497" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/crystal/" class="_nav-link" title="" style="margin-left:0;">Crystal</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _crystal">
				
				
<h1 id="transactions">Transactions</h1> <p>When working with databases, it is common to need to group operations in such a way that if one fails, then we can go back to the latest safe state. This solution is described in the <strong>transaction paradigm</strong>, and is implemented by most database engines as it is necessary to meet ACID properties (Atomicity, Consistency, Isolation, Durability) <sup><a href="#fn_ACID" id="reffn_ACID">ACID</a></sup></p> <p>With this in mind, we present the following example:</p> <p>We have two accounts (each represented by a name and an amount of money).</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
</pre> <p>In one moment a transfer is made from one account to the other. For example, <em>John transfers $50 to Sarah</em></p> <p>We have two accounts (each represented by a name and an amount of money).</p> <pre data-language="crystal">deposit db, "Sarah", 50
withdraw db, "John", 50
</pre> <p>It is important to have in mind that if one of the operations fails then the final state would be inconsistent. So we need to execute the <strong>two operations</strong> (deposit and withdraw) as <strong>one operation</strong>. And if an error occurs then we would like to go back in time as if that one operation was never executed.</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100

db.transaction do |tx|
  cnn = tx.connection

  transfer_amount = 1000
  deposit cnn, "Sarah", transfer_amount
  withdraw cnn, "John", transfer_amount
end
</pre> <p>In the above example, we start a transaction simply by calling the method <code>Database#transaction</code> (how we get the <code>database</code> object is encapsulated in the method <code>get_bank_db</code> and is out of the scope of this document). The <code>block</code> is the body of the transaction. When the <code>block</code> gets executed (without any error) then an <strong>implicit commit</strong> is finally executed to persist the changes in the database. If an exception is raised by one of the operations, then an <strong>implicit rollback</strong> is executed, bringing the database to the state before the transaction started.</p> <h2 id="exception-handling-and-rolling-back">Exception handling and rolling back</h2> <p>As we mentioned early, an <strong>implicit rollback</strong> gets executed when an exception is raised, and itâ€™s worth mentioning that the exception may be rescued by us.</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100

begin
  db.transaction do |tx|
    cnn = tx.connection

    transfer_amount = 1000
    deposit(cnn, "Sarah", transfer_amount)
    # John does not have enough money in his account!
    withdraw(cnn, "John", transfer_amount)
  end
rescue ex
  puts "Transfer has been rolled back due to: #{ex}"
end
</pre> <p>We may also raise an exception in the body of the transaction:</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100

begin
  db.transaction do |tx|
    cnn = tx.connection

    transfer_amount = 50
    deposit(cnn, "Sarah", transfer_amount)
    withdraw(cnn, "John", transfer_amount)
    raise Exception.new "Because ..."
  end
rescue ex
  puts "Transfer has been rolled back due to: #{ex}"
end
</pre> <p>As the previous example, the exception cause the transaction to rollback and then is rescued by us.</p> <p>There is one <code>exception</code> with a different behaviour. If a <code>DB::Rollback</code> is raised within the block, the implicit rollback will happen, but the exception will not be raised outside the block.</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100

begin
  db.transaction do |tx|
    cnn = tx.connection

    transfer_amount = 50
    deposit(cnn, "Sarah", transfer_amount)
    withdraw(cnn, "John", transfer_amount)

    # rollback exception
    raise DB::Rollback.new
  end
rescue ex
  # ex is never a DB::Rollback
end
</pre> <h2 id="explicit-commit-and-rollback">Explicit commit and rollback</h2> <p>In all the previous examples, the rolling back is <strong>implicit</strong>, but we can also tell the transaction to rollback:</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100

begin
  db.transaction do |tx|
    cnn = tx.connection

    transfer_amount = 50
    deposit(cnn, "Sarah", transfer_amount)
    withdraw(cnn, "John", transfer_amount)

    tx.rollback

    puts "Rolling Back the changes!"
  end
rescue ex
  # Notice that no exception is used in this case.
end
</pre> <p>And we can also use the <code>commit</code> method:</p> <pre data-language="crystal">db = get_bank_db

db.transaction do |tx|
  cnn = tx.connection

  transfer_amount = 50
  deposit(cnn, "Sarah", transfer_amount)
  withdraw(cnn, "John", transfer_amount)

  tx.commit
end
</pre> <p><strong>NOTE:</strong> After <code>commit</code> or <code>rollback</code> are used, the transaction is no longer usable. The connection is still open but any statement will be performed outside the context of the terminated transaction.</p> <h2 id="nested-transactions">Nested transactions</h2> <p>As the name suggests, a nested transaction is a transaction created inside the scope of another transaction. Here is an example:</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
create_account db, "Jack", amount: 0

begin
  db.transaction do |outer_tx|
    outer_cnn = outer_tx.connection

    transfer_amount = 50
    deposit(outer_cnn, "Sarah", transfer_amount)
    withdraw(outer_cnn, "John", transfer_amount)

    outer_tx.transaction do |inner_tx|
      inner_cnn = inner_tx.connection

      # John =&gt; 50 (pending commit)
      # Sarah =&gt; 150 (pending commit)
      # Jack =&gt; 0

      another_transfer_amount = 150
      deposit(inner_cnn, "Jack", another_transfer_amount)
      withdraw(inner_cnn, "Sarah", another_transfer_amount)
    end
  end
rescue ex
  puts "Exception raised due to: #{ex}"
end
</pre> <p>Some observations from the above example: the <code>inner_tx</code> works with the values updated although the <code>outer_tx</code> is pending the commit. The connection used by <code>outer_tx</code> and <code>inner_tx</code> is <strong>the same connection</strong>. This is because the <code>inner_tx</code> inherits the connection from the <code>outer_tx</code> when created.</p> <h3 id="rollback-nested-transactions">Rollback nested transactions</h3> <p>As weâ€™ve already seen, a rollback may be fired at any time (by an exception or by sending the message <code>rollback</code> explicitly)</p> <p>So letâ€™s present an example with a <strong>rollback fired by an exception placed at the outer-transaction</strong>:</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
create_account db, "Jack", amount: 0

begin
  db.transaction do |outer_tx|
    outer_cnn = outer_tx.connection

    transfer_amount = 50
    deposit(outer_cnn, "Sarah", transfer_amount)
    withdraw(outer_cnn, "John", transfer_amount)

    outer_tx.transaction do |inner_tx|
      inner_cnn = inner_tx.connection

      # John =&gt; 50 (pending commit)
      # Sarah =&gt; 150 (pending commit)
      # Jack =&gt; 0

      another_transfer_amount = 150
      deposit(inner_cnn, "Jack", another_transfer_amount)
      withdraw(inner_cnn, "Sarah", another_transfer_amount)
    end

    raise Exception.new("Rollback all the things!")
  end
rescue ex
  puts "Exception raised due to: #{ex}"
end
</pre> <p>The rollback place in the <code>outer_tx</code> block, rolled back all the changes including the ones in the <code>inner_tx</code> block (the same happens if we use an <strong>explicit</strong> rollback).</p> <p>If the <strong>rollback is fired by an exception at the inner_tx block</strong> all the changes including the ones in the <code>outer_tx</code> are rollbacked.</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
create_account db, "Jack", amount: 0

begin
  db.transaction do |outer_tx|
    outer_cnn = outer_tx.connection

    transfer_amount = 50
    deposit(outer_cnn, "Sarah", transfer_amount)
    withdraw(outer_cnn, "John", transfer_amount)

    outer_tx.transaction do |inner_tx|
      inner_cnn = inner_tx.connection

      # John =&gt; 50 (pending commit)
      # Sarah =&gt; 150 (pending commit)
      # Jack =&gt; 0

      another_transfer_amount = 150
      deposit(inner_cnn, "Jack", another_transfer_amount)
      withdraw(inner_cnn, "Sarah", another_transfer_amount)

      raise Exception.new("Rollback all the things!")
    end
  end
rescue ex
  puts "Exception raised due to: #{ex}"
end
</pre> <p>There is a way to rollback the changes in the <code>inner-transaction</code> but keep the ones in the <code>outer-transaction</code>. Use <code>rollback</code> in the <code>inner_tx</code> object. This will rollback <strong>only</strong> then inner-transaction. Here is the example:</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
create_account db, "Jack", amount: 0

begin
  db.transaction do |outer_tx|
    outer_cnn = outer_tx.connection

    transfer_amount = 50
    deposit(outer_cnn, "Sarah", transfer_amount)
    withdraw(outer_cnn, "John", transfer_amount)

    outer_tx.transaction do |inner_tx|
      inner_cnn = inner_tx.connection

      # John =&gt; 50 (pending commit)
      # Sarah =&gt; 150 (pending commit)
      # Jack =&gt; 0

      another_transfer_amount = 150
      deposit(inner_cnn, "Jack", another_transfer_amount)
      withdraw(inner_cnn, "Sarah", another_transfer_amount)

      inner_tx.rollback
    end
  end
rescue ex
  puts "Exception raised due to: #{ex}"
end
</pre> <p>The same happens if a <code>DB::Rollback</code> exception is raised in the <code>inner-transaction</code> block.</p> <pre data-language="crystal">db = get_bank_db

create_account db, "John", amount: 100
create_account db, "Sarah", amount: 100
create_account db, "Jack", amount: 0

begin
  db.transaction do |outer_tx|
    outer_cnn = outer_tx.connection

    transfer_amount = 50
    deposit(outer_cnn, "Sarah", transfer_amount)
    withdraw(outer_cnn, "John", transfer_amount)

    outer_tx.transaction do |inner_tx|
      inner_cnn = inner_tx.connection

      # John =&gt; 50 (pending commit)
      # Sarah =&gt; 150 (pending commit)
      # Jack =&gt; 0

      another_transfer_amount = 150
      deposit(inner_cnn, "Jack", another_transfer_amount)
      withdraw(inner_cnn, "Sarah", another_transfer_amount)

      # Rollback exception
      raise DB::Rollback.new
    end
  end
rescue ex
  puts "Exception raised due to: #{ex}"
end
</pre> <blockquote id="fn_ACID"> <sup>ACID</sup>. Theo Haerder and Andreas Reuter. 1983. Principles of transaction-oriented database recovery. ACM Comput. Surv. 15, 4 (December 1983), 287-317. DOI=<a href="http://dx.doi.org/10.1145/289.291" target="_blank">http://dx.doi.org/10.1145/289.291</a><a href="#reffn_ACID" title="Jump back to footnote [ACID] in the text."> â†©</a> </blockquote>
<div class="_attribution">
  <p class="_attribution-p">
    To the extent possible under law, the persons who contributed to this workhave waived<br>all copyright and related or neighboring rights to this workby associating CC0 with it.<br>
    <a href="https://crystal-lang.org/docs/database/transactions.html" class="_attribution-link">https://crystal-lang.org/docs/database/transactions.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
