
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Exceptions - Python 3.9 - W3cubDocs</title>
  
  <meta name="description" content=" Source code&#58; Lib&#47;asyncio&#47;exceptions.py ">
  <meta name="keywords" content="exceptions, python, python~3.9">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/python~3.9/library/asyncio-exceptions.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e498cd0ebe8746846fec95b1a53ab3bb0fb7f47f794f0a38f44c98a1f0d03b21d777ae2c583732e44a5a890f6eacb79a5333545db9d5f3616091ba21ca17d916.css">
  <script src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js" type="text/javascript"></script>
  <script src="/json/python~3.9.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/python~3.9/" class="_nav-link" title="" style="margin-left:0;">Python 3.9</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _python">
				
				
<h1 id="asyncio-exceptions">Exceptions</h1> <p id="exceptions"><strong>Source code:</strong> <a class="reference external" href="https://github.com/python/cpython/tree/3.9/Lib/asyncio/exceptions.py">Lib/asyncio/exceptions.py</a></p>  <dl class="exception"> <dt id="asyncio.TimeoutError">
<code>exception asyncio.TimeoutError</code> </dt> <dd>
<p>The operation has exceeded the given deadline.</p> <div class="admonition important"> <p class="admonition-title">Important</p> <p>This exception is different from the builtin <a class="reference internal" href="exceptions#TimeoutError" title="TimeoutError"><code>TimeoutError</code></a> exception.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="asyncio.CancelledError">
<code>exception asyncio.CancelledError</code> </dt> <dd>
<p>The operation has been cancelled.</p> <p>This exception can be caught to perform custom operations when asyncio Tasks are cancelled. In almost all situations the exception must be re-raised.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 3.8: </span><a class="reference internal" href="#asyncio.CancelledError" title="asyncio.CancelledError"><code>CancelledError</code></a> is now a subclass of <a class="reference internal" href="exceptions#BaseException" title="BaseException"><code>BaseException</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="asyncio.InvalidStateError">
<code>exception asyncio.InvalidStateError</code> </dt> <dd>
<p>Invalid internal state of <a class="reference internal" href="asyncio-task#asyncio.Task" title="asyncio.Task"><code>Task</code></a> or <a class="reference internal" href="asyncio-future#asyncio.Future" title="asyncio.Future"><code>Future</code></a>.</p> <p>Can be raised in situations like setting a result value for a <em>Future</em> object that already has a result value set.</p> </dd>
</dl> <dl class="exception"> <dt id="asyncio.SendfileNotAvailableError">
<code>exception asyncio.SendfileNotAvailableError</code> </dt> <dd>
<p>The “sendfile” syscall is not available for the given socket or file type.</p> <p>A subclass of <a class="reference internal" href="exceptions#RuntimeError" title="RuntimeError"><code>RuntimeError</code></a>.</p> </dd>
</dl> <dl class="exception"> <dt id="asyncio.IncompleteReadError">
<code>exception asyncio.IncompleteReadError</code> </dt> <dd>
<p>The requested read operation did not complete fully.</p> <p>Raised by the <a class="reference internal" href="asyncio-stream#asyncio-streams"><span class="std std-ref">asyncio stream APIs</span></a>.</p> <p>This exception is a subclass of <a class="reference internal" href="exceptions#EOFError" title="EOFError"><code>EOFError</code></a>.</p> <dl class="attribute"> <dt id="asyncio.IncompleteReadError.expected">
<code>expected</code> </dt> <dd>
<p>The total number (<a class="reference internal" href="functions#int" title="int"><code>int</code></a>) of expected bytes.</p> </dd>
</dl> <dl class="attribute"> <dt id="asyncio.IncompleteReadError.partial">
<code>partial</code> </dt> <dd>
<p>A string of <a class="reference internal" href="stdtypes#bytes" title="bytes"><code>bytes</code></a> read before the end of stream was reached.</p> </dd>
</dl> </dd>
</dl> <dl class="exception"> <dt id="asyncio.LimitOverrunError">
<code>exception asyncio.LimitOverrunError</code> </dt> <dd>
<p>Reached the buffer size limit while looking for a separator.</p> <p>Raised by the <a class="reference internal" href="asyncio-stream#asyncio-streams"><span class="std std-ref">asyncio stream APIs</span></a>.</p> <dl class="attribute"> <dt id="asyncio.LimitOverrunError.consumed">
<code>consumed</code> </dt> <dd>
<p>The total number of to be consumed bytes.</p> </dd>
</dl> </dd>
</dl>
<div class="_attribution">
  <p class="_attribution-p">
    © 2001–2020 Python Software Foundation<br>Licensed under the PSF License.<br>
    <a href="https://docs.python.org/3.9/library/asyncio-exceptions.html" class="_attribution-link">https://docs.python.org/3.9/library/asyncio-exceptions.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
