
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Python Development Mode - Python 3.9 - W3cubDocs</title>
  
  <meta name="description" content=" New in version 3.7. ">
  <meta name="keywords" content="python, development, modeeffects, moderesourcewarning, examplebad, file, descriptor, error, example, mode, python~3.9">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/python~3.9/library/devmode.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-e4ebd3a2a5652ff55173659804c4390a004917f3bdd17b5bb3ba78ea5c9c46fe181cadaac34517ccd815f5bdc982bbfe67179d6f4ac2f084ef2265e2a3dc8dc5.css" integrity="sha512-5OvToqVlL/VRc2WYBMQ5CgBJF/O90Xtbs7p46lycRv4YHK2qw0UXzNgV9b3Jgrv+Zxedb0rC8ITvImXio9yNxQ==" crossorigin="anonymous">
  <script type="text/javascript" integrity="sha512-EpkDeu98lN/jPKijllzVWdRg/dUSSMCaldYZNFz6bcNoBvpWRNz0HSTRQJ3ENmQc5Cuj1zDW1vHd7b0DzpOgyA==" crossorigin="anonymous" src="/assets/application-1299037aef7c94dfe33ca8a3965cd559d460fdd51248c09a95d619345cfa6dc36806fa5644dcf41d24d1409dc436641ce42ba3d730d6d6f1ddedbd03ce93a0c8.js"></script>
  <script src="/json/python~3.9.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script data-ad-client="ca-pub-2572770204602497" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/python~3.9/" class="_nav-link" title="" style="margin-left:0;">Python 3.9</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _python">
				
				
<h1 id="devmode">Python Development Mode</h1> <div class="versionadded" id="python-development-mode"> <p><span class="versionmodified added">New in version 3.7.</span></p> </div> <p>The Python Development Mode introduces additional runtime checks that are too expensive to be enabled by default. It should not be more verbose than the default if the code is correct; new warnings are only emitted when an issue is detected.</p> <p>It can be enabled using the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#id5"><code>-X dev</code></a> command line option or by setting the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONDEVMODE" id="index-0"><code>PYTHONDEVMODE</code></a> environment variable to <code>1</code>.</p>   <h1 id="effects-of-the-python-development-mode">Effects of the Python Development Mode</h1> <p>Enabling the Python Development Mode is similar to the following command, but with additional effects described below:</p> <pre data-language="python">PYTHONMALLOC=debug PYTHONASYNCIODEBUG=1 python3 -W default -X faulthandler
</pre> <p>Effects of the Python Development Mode:</p> <ul> <li>
<p>Add <code>default</code> <a class="reference internal" href="warnings#describing-warning-filters"><span class="std std-ref">warning filter</span></a>. The following warnings are shown:</p> <ul class="simple"> <li><a class="reference internal" href="exceptions#DeprecationWarning" title="DeprecationWarning"><code>DeprecationWarning</code></a></li> <li><a class="reference internal" href="exceptions#ImportWarning" title="ImportWarning"><code>ImportWarning</code></a></li> <li><a class="reference internal" href="exceptions#PendingDeprecationWarning" title="PendingDeprecationWarning"><code>PendingDeprecationWarning</code></a></li> <li><a class="reference internal" href="exceptions#ResourceWarning" title="ResourceWarning"><code>ResourceWarning</code></a></li> </ul> <p>Normally, the above warnings are filtered by the default <a class="reference internal" href="warnings#describing-warning-filters"><span class="std std-ref">warning filters</span></a>.</p> <p>It behaves as if the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#cmdoption-w"><code>-W default</code></a> command line option is used.</p> <p>Use the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#cmdoption-w"><code>-W error</code></a> command line option or set the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONWARNINGS" id="index-1"><code>PYTHONWARNINGS</code></a> environment variable to <code>error</code> to treat warnings as errors.</p> </li> <li>
<p>Install debug hooks on memory allocators to check for:</p> <ul class="simple"> <li>Buffer underflow</li> <li>Buffer overflow</li> <li>Memory allocator API violation</li> <li>Unsafe usage of the GIL</li> </ul> <p>See the <a class="reference internal" href="https://docs.python.org/3.9/c-api/memory.html#c.PyMem_SetupDebugHooks" title="PyMem_SetupDebugHooks"><code>PyMem_SetupDebugHooks()</code></a> C function.</p> <p>It behaves as if the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONMALLOC" id="index-2"><code>PYTHONMALLOC</code></a> environment variable is set to <code>debug</code>.</p> <p>To enable the Python Development Mode without installing debug hooks on memory allocators, set the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONMALLOC" id="index-3"><code>PYTHONMALLOC</code></a> environment variable to <code>default</code>.</p> </li> <li>
<p>Call <a class="reference internal" href="faulthandler#faulthandler.enable" title="faulthandler.enable"><code>faulthandler.enable()</code></a> at Python startup to install handlers for the <code>SIGSEGV</code>, <code>SIGFPE</code>, <code>SIGABRT</code>, <code>SIGBUS</code> and <code>SIGILL</code> signals to dump the Python traceback on a crash.</p> <p>It behaves as if the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#id5"><code>-X faulthandler</code></a> command line option is used or if the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONFAULTHANDLER" id="index-4"><code>PYTHONFAULTHANDLER</code></a> environment variable is set to <code>1</code>.</p> </li> <li>
<p>Enable <a class="reference internal" href="asyncio-dev#asyncio-debug-mode"><span class="std std-ref">asyncio debug mode</span></a>. For example, <a class="reference internal" href="asyncio#module-asyncio" title="asyncio: Asynchronous I/O."><code>asyncio</code></a> checks for coroutines that were not awaited and logs them.</p> <p>It behaves as if the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#envvar-PYTHONASYNCIODEBUG" id="index-5"><code>PYTHONASYNCIODEBUG</code></a> environment variable is set to <code>1</code>.</p> </li> <li>
<p>Check the <em>encoding</em> and <em>errors</em> arguments for string encoding and decoding operations. Examples: <a class="reference internal" href="functions#open" title="open"><code>open()</code></a>, <a class="reference internal" href="stdtypes#str.encode" title="str.encode"><code>str.encode()</code></a> and <a class="reference internal" href="stdtypes#bytes.decode" title="bytes.decode"><code>bytes.decode()</code></a>.</p> <p>By default, for best performance, the <em>errors</em> argument is only checked at the first encoding/decoding error and the <em>encoding</em> argument is sometimes ignored for empty strings.</p> </li> <li>The <a class="reference internal" href="io#io.IOBase" title="io.IOBase"><code>io.IOBase</code></a> destructor logs <code>close()</code> exceptions.</li> <li>Set the <code>dev_mode</code> attribute of <a class="reference internal" href="sys#sys.flags" title="sys.flags"><code>sys.flags</code></a> to <code>True</code>.</li> </ul> <p>The Python Development Mode does not enable the <a class="reference internal" href="tracemalloc#module-tracemalloc" title="tracemalloc: Trace memory allocations."><code>tracemalloc</code></a> module by default, because the overhead cost (to performance and memory) would be too large. Enabling the <a class="reference internal" href="tracemalloc#module-tracemalloc" title="tracemalloc: Trace memory allocations."><code>tracemalloc</code></a> module provides additional information on the origin of some errors. For example, <a class="reference internal" href="exceptions#ResourceWarning" title="ResourceWarning"><code>ResourceWarning</code></a> logs the traceback where the resource was allocated, and a buffer overflow error logs the traceback where the memory block was allocated.</p> <p>The Python Development Mode does not prevent the <a class="reference internal" href="https://docs.python.org/3.9/using/cmdline.html#cmdoption-o"><code>-O</code></a> command line option from removing <a class="reference internal" href="https://docs.python.org/3.9/reference/simple_stmts.html#assert"><code>assert</code></a> statements nor from setting <a class="reference internal" href="constants#__debug__" title="__debug__"><code>__debug__</code></a> to <code>False</code>.</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 3.8: </span>The <a class="reference internal" href="io#io.IOBase" title="io.IOBase"><code>io.IOBase</code></a> destructor now logs <code>close()</code> exceptions.</p> </div> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 3.9: </span>The <em>encoding</em> and <em>errors</em> arguments are now checked for string encoding and decoding operations.</p> </div>   <h1 id="resourcewarning-example">ResourceWarning Example</h1> <p>Example of a script counting the number of lines of the text file specified in the command line:</p> <pre data-language="python">import sys

def main():
    fp = open(sys.argv[1])
    nlines = len(fp.readlines())
    print(nlines)
    # The file is closed implicitly

if __name__ == "__main__":
    main()
</pre> <p>The script does not close the file explicitly. By default, Python does not emit any warning. Example using README.txt, which has 269 lines:</p> <pre data-language="shell">$ python3 script.py README.txt
269
</pre> <p>Enabling the Python Development Mode displays a <a class="reference internal" href="exceptions#ResourceWarning" title="ResourceWarning"><code>ResourceWarning</code></a> warning:</p> <pre data-language="shell">$ python3 -X dev script.py README.txt
269
script.py:10: ResourceWarning: unclosed file &lt;_io.TextIOWrapper name='README.rst' mode='r' encoding='UTF-8'&gt;
  main()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</pre> <p>In addition, enabling <a class="reference internal" href="tracemalloc#module-tracemalloc" title="tracemalloc: Trace memory allocations."><code>tracemalloc</code></a> shows the line where the file was opened:</p> <pre data-language="shell">$ python3 -X dev -X tracemalloc=5 script.py README.rst
269
script.py:10: ResourceWarning: unclosed file &lt;_io.TextIOWrapper name='README.rst' mode='r' encoding='UTF-8'&gt;
  main()
Object allocated at (most recent call last):
  File "script.py", lineno 10
    main()
  File "script.py", lineno 4
    fp = open(sys.argv[1])
</pre> <p>The fix is to close explicitly the file. Example using a context manager:</p> <pre data-language="python">def main():
    # Close the file explicitly when exiting the with block
    with open(sys.argv[1]) as fp:
        nlines = len(fp.readlines())
    print(nlines)
</pre> <p>Not closing a resource explicitly can leave a resource open for way longer than expected; it can cause severe issues upon exiting Python. It is bad in CPython, but it is even worse in PyPy. Closing resources explicitly makes an application more deterministic and more reliable.</p>   <h1 id="bad-file-descriptor-error-example">Bad file descriptor error example</h1> <p>Script displaying the first line of itself:</p> <pre data-language="python">import os

def main():
    fp = open(__file__)
    firstline = fp.readline()
    print(firstline.rstrip())
    os.close(fp.fileno())
    # The file is closed implicitly

main()
</pre> <p>By default, Python does not emit any warning:</p> <pre data-language="shell">$ python3 script.py
import os
</pre> <p>The Python Development Mode shows a <a class="reference internal" href="exceptions#ResourceWarning" title="ResourceWarning"><code>ResourceWarning</code></a> and logs a “Bad file descriptor” error when finalizing the file object:</p> <pre data-language="shell">$ python3 script.py
import os
script.py:10: ResourceWarning: unclosed file &lt;_io.TextIOWrapper name='script.py' mode='r' encoding='UTF-8'&gt;
  main()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: &lt;_io.TextIOWrapper name='script.py' mode='r' encoding='UTF-8'&gt;
Traceback (most recent call last):
  File "script.py", line 10, in &lt;module&gt;
    main()
OSError: [Errno 9] Bad file descriptor
</pre> <p><code>os.close(fp.fileno())</code> closes the file descriptor. When the file object finalizer tries to close the file descriptor again, it fails with the <code>Bad
file descriptor</code> error. A file descriptor must be closed only once. In the worst case scenario, closing it twice can lead to a crash (see <a class="reference external" href="https://bugs.python.org/issue18748">bpo-18748</a> for an example).</p> <p>The fix is to remove the <code>os.close(fp.fileno())</code> line, or open the file with <code>closefd=False</code>.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © 2001–2020 Python Software Foundation<br>Licensed under the PSF License.<br>
    <a href="https://docs.python.org/3.9/library/devmode.html" class="_attribution-link">https://docs.python.org/3.9/library/devmode.html</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
